(function (global) {
var ns = global.AccountingManagerApp = global.AccountingManagerApp || {};

  ns.createPaymentCreateModule = function (deps) {
    var FIELD_CANDIDATES = deps.FIELD_CANDIDATES;
    var PAYMENT_MOVEMENT_TYPES = deps.PAYMENT_MOVEMENT_TYPES;
    var MODULES = deps.MODULES;
    var ENSURE_SUPPLIER_ACCOUNTING_ACCOUNT_FUNCTION = deps.ENSURE_SUPPLIER_ACCOUNTING_ACCOUNT_FUNCTION;
    var ENSURE_SUPPLIER_PAYMENT_ACCOUNT_FUNCTION = deps.ENSURE_SUPPLIER_PAYMENT_ACCOUNT_FUNCTION;
    var state = deps.state;
    var elements = deps.elements;
    var helpers = deps.helpers;
    var crm = deps.crm;
    var renderer = deps.renderer;
    var renderAll = deps.renderAll;
    var debugError = deps.debugError;
    var buildInvoicesView = deps.buildInvoicesView;
    var isBlockedInvoicePaymentStatus = deps.isBlockedInvoicePaymentStatus;
    var getInvoiceType = deps.getInvoiceType;
    var isCreditNoteInvoice = deps.isCreditNoteInvoice;
    var getInvoiceSupplierId = deps.getInvoiceSupplierId;
    var getSupplierNameFromInvoice = deps.getSupplierNameFromInvoice;
    var getBookingIdFromInvoice = deps.getBookingIdFromInvoice;
    var getBookingNameFromInvoice = deps.getBookingNameFromInvoice;
    var getInvoiceSettlementId = deps.getInvoiceSettlementId;
    var getInvoiceSettlementName = deps.getInvoiceSettlementName;
    var getInvoicePaidAmount = deps.getInvoicePaidAmount;
    var getMfspFromInvoice = deps.getMfspFromInvoice;
    var buildPaymentContextSummaryText = deps.buildPaymentContextSummaryText;
    var getUniqueSortedValues = deps.getUniqueSortedValues;
    var roundCurrency = deps.roundCurrency;
    var getLocalIsoDate = deps.getLocalIsoDate;
    var buildDefaultPaymentReference = deps.buildDefaultPaymentReference;
    var getPaymentAccountOwnerSupplierId = deps.getPaymentAccountOwnerSupplierId;
    var getPaymentAccountIbanValue = deps.getPaymentAccountIbanValue;
    var getPaymentAccountBeneficiaryName = deps.getPaymentAccountBeneficiaryName;
    var getPaymentAccountRecordById = deps.getPaymentAccountRecordById;
    var getSupplierRecordById = deps.getSupplierRecordById;
    var getSupplierDefaultPaymentAccountId = deps.getSupplierDefaultPaymentAccountId;
    var paymentAccountBelongsToSupplier = deps.paymentAccountBelongsToSupplier;
    var isSelectablePaymentAccount = deps.isSelectablePaymentAccount;
    var isOwnPaymentAccount = deps.isOwnPaymentAccount;
    var ensurePaymentAccountsLoaded = deps.ensurePaymentAccountsLoaded;
    var ensurePayAllocationsLoaded = deps.ensurePayAllocationsLoaded;
    var ensureSupplierDefaultPaymentAccountAssigned = deps.ensureSupplierDefaultPaymentAccountAssigned;
    var refreshInvoicesTabData = deps.refreshInvoicesTabData;
    var refreshPaymentsTabData = deps.refreshPaymentsTabData;
    var loadInvoicesForSupplier = deps.loadInvoicesForSupplier;
    var loadPaymentsForSupplier = deps.loadPaymentsForSupplier;
    var resetPaymentRelationshipIndexes = deps.resetPaymentRelationshipIndexes;
    var assertCrmMutationSucceeded = deps.assertCrmMutationSucceeded;
    var getFunctionOutputObject = deps.getFunctionOutputObject;
    var getFunctionResponseResult = deps.getFunctionResponseResult;
    var recalculateSettlementTotalsForSettlementIds = deps.recalculateSettlementTotalsForSettlementIds;
    var syncAccountingEntriesForInvoices = deps.syncAccountingEntriesForInvoices;
    var syncAccountingEntryForPayment = deps.syncAccountingEntryForPayment;
    var getUniqueSettlementIdsFromInvoices = deps.getUniqueSettlementIdsFromInvoices;
    var invalidateInvoiceCreateSettlementCache = deps.invalidateInvoiceCreateSettlementCache;
    var ensureInvoiceAllocationsLoaded = deps.ensureInvoiceAllocationsLoaded;

    function resetInvoicePaymentForm() {
      var paymentDate = "";
      var defaultReference = buildDefaultPaymentReference(paymentDate);

      state.paymentCreation.context = null;
      state.paymentCreation.form = {
        name: defaultReference,
        lastAutoGeneratedName: defaultReference,
        paymentDate: paymentDate,
        headerPaymentAccountId: "",
        headerPaymentAccountQuery: "",
        headerPaymentAccountDropdownOpen: false,
        movementType: "",
        status: "Paid",
        accountingStatus: "Pending",
        paymentAccountsBySupplier: {},
        allocations: {}
      };
    }

    function buildInvoicePaymentContext(selectedInvoices) {
      var blockedStatuses = [];
      var zeroPendingInvoices = [];
      var normalInvoiceNumbers = [];
      var creditNoteInvoiceNumbers = [];
      var context;
      var supplierContextsByKey = {};

      if (!selectedInvoices || !selectedInvoices.length) {
        return {
          error: "Select at least one invoice with the checkbox before creating a payment."
        };
      }

      context = {
        supplierId: "",
        supplierName: "",
        bookingId: "",
        bookingName: "",
        settlementId: "",
        settlementName: "",
        ezusReference: "",
        supplierIds: [],
        supplierNames: [],
        bookingIds: [],
        bookingNames: [],
        settlementIds: [],
        settlementNames: [],
        mfsps: [],
        ezusReferences: [],
        suppliers: [],
        invoices: [],
        invoiceCount: selectedInvoices.length,
        totalAmount: 0
      };

      selectedInvoices.forEach(function (invoice) {
        var invoiceNumber = helpers.getInvoiceDisplayNumber(invoice, FIELD_CANDIDATES);
        var pendingAmount = roundCurrency(helpers.getInvoicePendingAmount(invoice, FIELD_CANDIDATES));
        var status = String(invoice.Status || "");
        var invoiceType = getInvoiceType(invoice);
        var isCreditNote = isCreditNoteInvoice(invoice);
        var supplierId = getInvoiceSupplierId(invoice);
        var supplierName = getSupplierNameFromInvoice(invoice);
        var bookingId = getBookingIdFromInvoice(invoice);
        var bookingName = getBookingNameFromInvoice(invoice) || "";
        var settlementId = getInvoiceSettlementId(invoice);
        var settlementName = getInvoiceSettlementName(invoice) || "";
        var mfsp = getMfspFromInvoice(invoice) || "";
        var ezusReference = invoice.Ezus_Supplier_Reference || "";
        var supplierContextKey = supplierId || (supplierName ? "supplier-name:" + supplierName : "invoice:" + invoice.id);
        var supplierContext;

        if (isBlockedInvoicePaymentStatus(status)) {
          blockedStatuses.push(invoiceNumber + " (" + helpers.textValue(status) + ")");
        }

        if (pendingAmount <= 0) {
          zeroPendingInvoices.push(invoiceNumber);
        }

        if (isCreditNote) {
          creditNoteInvoiceNumbers.push(invoiceNumber);
        } else {
          normalInvoiceNumbers.push(invoiceNumber);
        }

        if (supplierId) {
          context.supplierIds.push(supplierId);
        }
        if (supplierName) {
          context.supplierNames.push(supplierName);
        }
        if (bookingId) {
          context.bookingIds.push(bookingId);
        }
        if (bookingName) {
          context.bookingNames.push(bookingName);
        }
        if (settlementId) {
          context.settlementIds.push(settlementId);
        }
        if (settlementName) {
          context.settlementNames.push(settlementName);
        }
        if (mfsp) {
          context.mfsps.push(mfsp);
        }
        if (ezusReference) {
          context.ezusReferences.push(ezusReference);
        }

        if (!supplierContextsByKey[supplierContextKey]) {
          supplierContextsByKey[supplierContextKey] = {
            key: supplierContextKey,
            id: supplierId,
            name: supplierName || "Unknown supplier",
            bookingNames: [],
            settlementNames: [],
            mfsps: [],
            invoiceIds: [],
            invoiceNumbers: [],
            invoiceCount: 0,
            totalAmount: 0
          };
        }

        supplierContext = supplierContextsByKey[supplierContextKey];
        supplierContext.bookingNames.push(bookingName);
        supplierContext.settlementNames.push(settlementName);
        supplierContext.mfsps.push(mfsp);
        supplierContext.invoiceIds.push(invoice.id);
        supplierContext.invoiceNumbers.push(invoiceNumber);
        supplierContext.invoiceCount += 1;
        supplierContext.totalAmount += pendingAmount;

        context.invoices.push({
          id: invoice.id,
          number: invoiceNumber,
          invoiceType: invoiceType,
          isCreditNote: isCreditNote,
          date: invoice.Invoice_Date,
          supplierId: supplierId,
          supplierName: supplierName,
          bookingName: bookingName,
          settlementName: settlementName,
          mfsp: mfsp,
          pendingAmount: pendingAmount
        });
        context.totalAmount += pendingAmount;
      });

      context.totalAmount = roundCurrency(context.totalAmount);
      context.supplierIds = getUniqueSortedValues(context.supplierIds);
      context.supplierNames = getUniqueSortedValues(context.supplierNames);
      context.bookingIds = getUniqueSortedValues(context.bookingIds);
      context.bookingNames = getUniqueSortedValues(context.bookingNames);
      context.settlementIds = getUniqueSortedValues(context.settlementIds);
      context.settlementNames = getUniqueSortedValues(context.settlementNames);
      context.mfsps = getUniqueSortedValues(context.mfsps);
      context.ezusReferences = getUniqueSortedValues(context.ezusReferences);
      context.suppliers = Object.keys(supplierContextsByKey).map(function (key) {
        var supplierContext = supplierContextsByKey[key];

        supplierContext.bookingNames = getUniqueSortedValues(supplierContext.bookingNames);
        supplierContext.settlementNames = getUniqueSortedValues(supplierContext.settlementNames);
        supplierContext.mfsps = getUniqueSortedValues(supplierContext.mfsps);
        supplierContext.invoiceNumbers = getUniqueSortedValues(supplierContext.invoiceNumbers);
        supplierContext.totalAmount = roundCurrency(supplierContext.totalAmount);
        supplierContext.bookingDisplay = deps.getContextDisplayValue(supplierContext.bookingNames, "bookings", 3);
        supplierContext.settlementDisplay = deps.getContextDisplayValue(supplierContext.settlementNames, "settlements", 3);
        supplierContext.mfspDisplay = deps.getContextDisplayValue(supplierContext.mfsps, "MFSPs", 3);

        return supplierContext;
      }).sort(function (left, right) {
        return String(left.name || "").localeCompare(String(right.name || ""), "en", {
          sensitivity: "base"
        });
      });
      context.supplierId = context.supplierIds.length === 1 ? context.supplierIds[0] : "";
      context.supplierName = context.supplierNames.length === 1 ? context.supplierNames[0] : "";
      context.bookingId = context.bookingIds.length === 1 ? context.bookingIds[0] : "";
      context.bookingName = context.bookingNames.length === 1 ? context.bookingNames[0] : "";
      context.settlementId = context.settlementIds.length === 1 ? context.settlementIds[0] : "";
      context.settlementName = context.settlementNames.length === 1 ? context.settlementNames[0] : "";
      context.ezusReference = context.ezusReferences.length === 1 ? context.ezusReferences[0] : "";
      context.movementType = creditNoteInvoiceNumbers.length && !normalInvoiceNumbers.length
        ? PAYMENT_MOVEMENT_TYPES.supplierRefund
        : PAYMENT_MOVEMENT_TYPES.outbound;
      context.hasMixedInvoiceTypes = normalInvoiceNumbers.length > 0 && creditNoteInvoiceNumbers.length > 0;
      context.actionLabel = context.movementType === PAYMENT_MOVEMENT_TYPES.supplierRefund ? "refund" : "payment";
      context.contextMode = (
        context.supplierNames.length <= 1 &&
        context.bookingNames.length <= 1 &&
        context.settlementNames.length <= 1
      ) ? "Single" : "Mixed";
      context.contextSummary = buildPaymentContextSummaryText(context);
      context.supplierDisplay = deps.getContextDisplayValue(context.supplierNames, "suppliers");
      context.bookingDisplay = deps.getContextDisplayValue(context.bookingNames, "bookings");
      context.settlementDisplay = deps.getContextDisplayValue(context.settlementNames, "settlements");

      if (blockedStatuses.length) {
        return {
          error: "These invoices cannot be paid from this form because their status is not payable: " + blockedStatuses.join(", ") + "."
        };
      }

      if (zeroPendingInvoices.length) {
        return {
          error: "These invoices no longer have pending amount to allocate: " + zeroPendingInvoices.join(", ") + "."
        };
      }

      return {
        context: context
      };
    }

    function buildDefaultInvoicePaymentForm(context) {
      var allocations = {};
      var paymentAccountsBySupplier = {};
      var paymentDate = "";
      var defaultReference = buildDefaultPaymentReference(paymentDate);

      (context && context.invoices ? context.invoices : []).forEach(function (invoice) {
        allocations[invoice.id] = roundCurrency(invoice.pendingAmount);
      });

      (context && context.suppliers ? context.suppliers : []).forEach(function (supplierContext) {
        if (supplierContext.id) {
          paymentAccountsBySupplier[supplierContext.id] = getPreferredPaymentAccountIdForSupplier(supplierContext.id);
        }
      });

      return {
        name: defaultReference,
        lastAutoGeneratedName: defaultReference,
        paymentDate: paymentDate,
        headerPaymentAccountId: "",
        headerPaymentAccountQuery: "",
        headerPaymentAccountDropdownOpen: false,
        movementType: context && context.movementType ? context.movementType : PAYMENT_MOVEMENT_TYPES.outbound,
        status: "Paid",
        accountingStatus: "Pending",
        paymentAccountsBySupplier: paymentAccountsBySupplier,
        allocations: allocations
      };
    }

    function getInvoicePaymentSelectedAmount(context, allocations) {
      return roundCurrency((context && context.invoices ? context.invoices : []).reduce(function (sum, invoice) {
        var rawValue = allocations && allocations[invoice.id] !== undefined ? allocations[invoice.id] : invoice.pendingAmount;
        var parsedValue = Number(rawValue);
        return sum + (Number.isFinite(parsedValue) && parsedValue > 0 ? parsedValue : 0);
      }, 0));
    }

    function getInvoicePaymentNetAmount(context, allocations) {
      return roundCurrency((context && context.invoices ? context.invoices : []).reduce(function (sum, invoice) {
        var rawValue = allocations && allocations[invoice.id] !== undefined ? allocations[invoice.id] : invoice.pendingAmount;
        var parsedValue = Number(rawValue);
        var amount = Number.isFinite(parsedValue) && parsedValue > 0 ? parsedValue : 0;
        return sum + (invoice.isCreditNote ? -amount : amount);
      }, 0));
    }

    function getSupplierPaymentSelectedAmount(supplierContext, allocations, invoices) {
      return roundCurrency((invoices || []).reduce(function (sum, invoice) {
        var rawValue;
        var parsedValue;

        if (supplierContext && supplierContext.id) {
          if (String(invoice.supplierId || "") !== String(supplierContext.id)) {
            return sum;
          }
        } else if (String(invoice.supplierName || "") !== String(supplierContext && supplierContext.name || "")) {
          return sum;
        }

        rawValue = allocations && allocations[invoice.id] !== undefined ? allocations[invoice.id] : invoice.pendingAmount;
        parsedValue = Number(rawValue);
        return sum + (Number.isFinite(parsedValue) && parsedValue > 0 ? parsedValue : 0);
      }, 0));
    }

    function getAvailableHeaderPaymentAccounts() {
      return state.records.paymentAccounts.filter(isOwnPaymentAccount).sort(function (left, right) {
        return String(helpers.getCandidateValue(left, FIELD_CANDIDATES.paymentAccount.name) || left.Name || "").localeCompare(
          String(helpers.getCandidateValue(right, FIELD_CANDIDATES.paymentAccount.name) || right.Name || ""),
          "en",
          { sensitivity: "base" }
        );
      });
    }

    function getHeaderPaymentAccountOptionLabel(account) {
      var name = helpers.getCandidateValue(account, FIELD_CANDIDATES.paymentAccount.name) || account.Name || account.id;
      var email = helpers.textValue(account && account.Email, "");
      var iban = getPaymentAccountIbanValue(account);

      return [name, email, iban].filter(Boolean).join(" | ");
    }

    function getSelectedHeaderPaymentAccountRecord() {
      return getPaymentAccountRecordById(state.paymentCreation.form.headerPaymentAccountId);
    }

    function getSelectedHeaderPaymentAccountLabel() {
      var selectedAccount = getSelectedHeaderPaymentAccountRecord();

      return selectedAccount ? getHeaderPaymentAccountOptionLabel(selectedAccount) : "";
    }

    function closeInvoicePaymentHeaderAccountDropdown() {
      state.paymentCreation.form.headerPaymentAccountDropdownOpen = false;
    }

    function getFilteredHeaderPaymentAccounts(query) {
      var normalizedQuery = helpers.normalizeQuery(query);

      return getAvailableHeaderPaymentAccounts().filter(function (account) {
        if (!normalizedQuery) {
          return true;
        }

        return helpers.matchesText(
          getHeaderPaymentAccountOptionLabel(account),
          normalizedQuery
        );
      });
    }

    function syncInvoicePaymentHeaderAccountInputValue() {
      var query = String(state.paymentCreation.form.headerPaymentAccountQuery || "");
      var selectedLabel = getSelectedHeaderPaymentAccountLabel();

      if (!query && selectedLabel) {
        elements.invoicePaymentAccount.value = selectedLabel;
        return;
      }

      elements.invoicePaymentAccount.value = query;
    }

    function selectInvoicePaymentHeaderAccount(accountId) {
      var selectedAccount = getPaymentAccountRecordById(accountId);

      state.paymentCreation.form.headerPaymentAccountId = selectedAccount ? accountId : "";
      state.paymentCreation.form.headerPaymentAccountQuery = selectedAccount ? getHeaderPaymentAccountOptionLabel(selectedAccount) : "";
      closeInvoicePaymentHeaderAccountDropdown();
      renderInvoicePaymentPanel();
    }

    function onInvoicePaymentHeaderAccountFocus() {
      state.paymentCreation.form.headerPaymentAccountDropdownOpen = true;
      renderInvoicePaymentPanel();
    }

    function onInvoicePaymentHeaderAccountInput() {
      state.paymentCreation.form.headerPaymentAccountQuery = elements.invoicePaymentAccount.value || "";
      state.paymentCreation.form.headerPaymentAccountDropdownOpen = true;
      state.paymentCreation.form.headerPaymentAccountId = "";
      renderInvoicePaymentPanel();
    }

    function onInvoicePaymentHeaderAccountKeydown(event) {
      var filteredAccounts;

      if (!event) {
        return;
      }

      if (event.key === "Enter") {
        filteredAccounts = getFilteredHeaderPaymentAccounts(state.paymentCreation.form.headerPaymentAccountQuery);
        if (filteredAccounts.length) {
          event.preventDefault();
          selectInvoicePaymentHeaderAccount(filteredAccounts[0].id);
        }
        return;
      }

      if (event.key === "Escape") {
        closeInvoicePaymentHeaderAccountDropdown();
        renderInvoicePaymentPanel();
        return;
      }

      if (event.key === "ArrowDown") {
        state.paymentCreation.form.headerPaymentAccountDropdownOpen = true;
        renderInvoicePaymentPanel();
      }
    }

    function onInvoicePaymentHeaderAccountBlur() {
      global.setTimeout(function () {
        closeInvoicePaymentHeaderAccountDropdown();
        renderInvoicePaymentPanel();
      }, 120);
    }

    function onInvoicePaymentHeaderAccountToggleClick() {
      state.paymentCreation.form.headerPaymentAccountDropdownOpen = !state.paymentCreation.form.headerPaymentAccountDropdownOpen;
      if (state.paymentCreation.form.headerPaymentAccountDropdownOpen && !state.paymentCreation.form.headerPaymentAccountQuery) {
        state.paymentCreation.form.headerPaymentAccountQuery = elements.invoicePaymentAccount.value || "";
      }
      renderInvoicePaymentPanel();
    }

    function getInvoicePaymentHeaderAccountIdFromEvent(event) {
      var target = event.target;
      var accountId = target && target.getAttribute ? target.getAttribute("data-payment-header-account-id") : "";

      if (!accountId && target && target.closest) {
        target = target.closest("[data-payment-header-account-id]");
        accountId = target ? target.getAttribute("data-payment-header-account-id") : "";
      }

      return accountId;
    }

    function onInvoicePaymentHeaderAccountDropdownPointerDown(event) {
      var accountId = getInvoicePaymentHeaderAccountIdFromEvent(event);

      if (!accountId) {
        return;
      }

      // Confirm the choice before the input blur can close and re-render the menu.
      event.preventDefault();
      selectInvoicePaymentHeaderAccount(accountId);
    }

    function onInvoicePaymentHeaderAccountDropdownClick(event) {
      var accountId = getInvoicePaymentHeaderAccountIdFromEvent(event);

      if (!accountId) {
        return;
      }

      selectInvoicePaymentHeaderAccount(accountId);
    }

    function getAllowedPaymentAccountsForSupplier(supplierId) {
      var normalizedSupplierId = String(supplierId || "").trim();
      var allowedAccounts = state.records.paymentAccounts.filter(isSelectablePaymentAccount);

      return allowedAccounts.filter(function (account) {
        var ownerSupplierId = getPaymentAccountOwnerSupplierId(account);

        if (paymentAccountBelongsToSupplier(account, supplierId, "")) {
          return true;
        }

        if (!ownerSupplierId) {
          return true;
        }

        return normalizedSupplierId && ownerSupplierId === normalizedSupplierId;
      }).sort(function (left, right) {
        return getHeaderPaymentAccountOptionLabel(left).localeCompare(getHeaderPaymentAccountOptionLabel(right), "en", {
          sensitivity: "base"
        });
      });
    }

    function getPreferredPaymentAccountIdForSupplier(supplierId) {
      var normalizedSupplierId = String(supplierId || "").trim();
      var supplierRecord;
      var defaultPaymentAccountId;
      var supplierAccounts;
      var normalizedPaymentAccountId;
      var paymentAccountRecord;

      if (!normalizedSupplierId) {
        return "";
      }

      supplierRecord = getSupplierRecordById(supplierId);
      defaultPaymentAccountId = getSupplierDefaultPaymentAccountId(supplierRecord);

      if (defaultPaymentAccountId && getAllowedPaymentAccountsForSupplier(supplierId).some(function (account) {
        return String(account && account.id || "") === String(defaultPaymentAccountId);
      })) {
        return defaultPaymentAccountId;
      }

      supplierAccounts = getAllowedPaymentAccountsForSupplier(supplierId).filter(function (account) {
        return paymentAccountBelongsToSupplier(account, supplierId, "");
      });

      if (supplierAccounts.length) {
        return String(supplierAccounts[0].id || "");
      }

      if (supplierRecord) {
        normalizedPaymentAccountId = String(defaultPaymentAccountId || "").trim();
        if (normalizedPaymentAccountId) {
          paymentAccountRecord = getPaymentAccountRecordById(normalizedPaymentAccountId);
          if (paymentAccountRecord) {
            return normalizedPaymentAccountId;
          }
        }
      }

      return "";
    }

    function getSupplierPaymentAccountPlaceholder(supplierContext, accounts) {
      var supplierAccounts = (accounts || []).filter(function (account) {
        return paymentAccountBelongsToSupplier(
          account,
          supplierContext && supplierContext.id ? supplierContext.id : "",
          supplierContext && supplierContext.name ? supplierContext.name : ""
        );
      });

      if (!supplierContext || !supplierContext.id) {
        return "No supplier record available";
      }

      if (supplierAccounts.length) {
        return "Auto-assign supplier payment account";
      }

      if ((accounts || []).length) {
        return "Auto-create or choose shared account";
      }

      return "Auto-create supplier payment account";
    }

    function renderInvoicePaymentPanel() {
      var isOpen = state.paymentCreation.isOpen;
      var context = state.paymentCreation.context;
      var form = state.paymentCreation.form;
      var totalAmount = getInvoicePaymentSelectedAmount(context, form.allocations);
      var netAmount = getInvoicePaymentNetAmount(context, form.allocations);
      var supplierAccountRows = "";
      var headerPaymentAccounts = getAvailableHeaderPaymentAccounts();
      var filteredHeaderPaymentAccounts = getFilteredHeaderPaymentAccounts(form.headerPaymentAccountQuery);
      var selectedHeaderPaymentAccountId = String(form.headerPaymentAccountId || "").trim();
      var selectedHeaderPaymentAccountIsValid;
      var headerPaymentAccountDropdownMarkup = "";

      elements.invoicePaymentPanel.hidden = !isOpen;

      if (!isOpen) {
        return;
      }

      elements.invoicePaymentModeBadge.textContent = context
        ? context.contextMode + " context | " + context.invoiceCount + (context.invoiceCount === 1 ? " invoice selected" : " invoices selected")
        : "Selection required";
      elements.invoicePaymentSupplier.value = context ? helpers.textValue(context.supplierDisplay, "") : "";
      elements.invoicePaymentBooking.value = context ? helpers.textValue(context.bookingDisplay, "") : "";
      elements.invoicePaymentSettlement.value = context ? helpers.textValue(context.settlementDisplay, "") : "";
      elements.invoicePaymentSelectedCount.textContent = context
        ? context.invoiceCount + (context.invoiceCount === 1 ? " invoice" : " invoices")
        : "0 invoices";
      elements.invoicePaymentSelectedList.textContent = context && context.invoices.length
        ? context.invoices.map(function (invoice) {
          return invoice.number;
        }).join(", ")
        : "-";
      elements.invoicePaymentTotalAmount.textContent = helpers.formatCurrency(context && context.hasMixedInvoiceTypes ? Math.abs(netAmount) : totalAmount);
      elements.invoicePaymentName.value = form.name || "";
      elements.invoicePaymentDate.value = form.paymentDate || "";
      selectedHeaderPaymentAccountIsValid = headerPaymentAccounts.some(function (account) {
        return String(account && account.id || "") === selectedHeaderPaymentAccountId;
      });
      if (!selectedHeaderPaymentAccountIsValid) {
        selectedHeaderPaymentAccountId = "";
        form.headerPaymentAccountId = "";
        form.headerPaymentAccountQuery = "";
      }
      syncInvoicePaymentHeaderAccountInputValue();
      if (context && !context.hasMixedInvoiceTypes && context.movementType && form.movementType !== context.movementType) {
        form.movementType = context.movementType;
      }
      elements.invoicePaymentAccount.placeholder = headerPaymentAccounts.length
        ? "Search payment account"
        : "No Own payment accounts available";
      elements.invoicePaymentAccount.setAttribute(
        "aria-expanded",
        form.headerPaymentAccountDropdownOpen && headerPaymentAccounts.length ? "true" : "false"
      );
      if (!headerPaymentAccounts.length) {
        headerPaymentAccountDropdownMarkup = '<div class="settlement-dropdown-empty">No Own payment accounts available.</div>';
      } else if (!filteredHeaderPaymentAccounts.length) {
        headerPaymentAccountDropdownMarkup = '<div class="settlement-dropdown-empty">No payment accounts match this search.</div>';
      } else {
        headerPaymentAccountDropdownMarkup = filteredHeaderPaymentAccounts.map(function (account) {
          var isSelected = String(account && account.id || "") === selectedHeaderPaymentAccountId;

          return [
            '<button class="settlement-option' + (isSelected ? " is-selected" : "") + '" type="button" role="option" aria-selected="' + (isSelected ? "true" : "false") + '" data-payment-header-account-id="' + helpers.escapeHtml(account.id) + '">',
            '  <span class="settlement-option-title">' + helpers.escapeHtml(helpers.getCandidateValue(account, FIELD_CANDIDATES.paymentAccount.name) || account.Name || account.id) + "</span>",
            '  <span class="settlement-option-meta">' + helpers.escapeHtml([
              helpers.textValue(account && account.Bank_Name, ""),
              helpers.textValue(account && account.Email, ""),
              getPaymentAccountIbanValue(account)
            ].filter(Boolean).join(" | ") || "-") + "</span>",
            "</button>"
          ].join("");
        }).join("");
      }
      elements.invoicePaymentAccountDropdown.innerHTML = headerPaymentAccountDropdownMarkup;
      elements.invoicePaymentAccountDropdown.hidden = !form.headerPaymentAccountDropdownOpen;
      elements.invoicePaymentMovementType.value = context && context.hasMixedInvoiceTypes
        ? "Mixed settlement (net " + (getInvoicePaymentNetAmount(context, form.allocations) < 0 ? "supplier refund" : "outbound payment") + ")"
        : form.movementType || (context ? context.movementType : "") || "";
      elements.invoicePaymentStatus.value = form.status || "Paid";
      elements.invoicePaymentAccountingStatus.value = form.accountingStatus || "Pending";
      supplierAccountRows = context && context.suppliers.length ? context.suppliers.map(function (supplierContext) {
        var availableAccounts = getAllowedPaymentAccountsForSupplier(supplierContext.id);
        var allocatedAmount = getSupplierPaymentSelectedAmount(supplierContext, form.allocations, context.invoices);
        var selectedAccountId = form.paymentAccountsBySupplier && supplierContext.id
          ? String(form.paymentAccountsBySupplier[supplierContext.id] || "")
          : "";
        var selectOptions = [
          '<option value="">' + helpers.escapeHtml(getSupplierPaymentAccountPlaceholder(supplierContext, availableAccounts)) + "</option>"
        ];

        availableAccounts.forEach(function (account) {
          var accountLabel = helpers.getCandidateValue(account, FIELD_CANDIDATES.paymentAccount.name) || account.Name || account.id;
          var email = helpers.textValue(account.Email, "");
          var ownerLabel = getPaymentAccountOwnerSupplierId(account) === supplierContext.id ? "Supplier" : "Shared";

          selectOptions.push(
            '<option value="' + helpers.escapeHtml(account.id) + '"' +
            (String(account.id) === selectedAccountId ? " selected" : "") +
            ">" + helpers.escapeHtml(email ? ownerLabel + " | " + accountLabel + " | " + email : ownerLabel + " | " + accountLabel) + "</option>"
          );
        });

        return [
          "<tr>",
          '  <td><strong>' + helpers.escapeHtml(supplierContext.name || "-") + "</strong></td>",
          '  <td class="payment-context-cell">' + helpers.escapeHtml(supplierContext.bookingDisplay || "-") + "</td>",
          '  <td class="payment-context-cell">' + helpers.escapeHtml(supplierContext.mfspDisplay || "-") + "</td>",
          '  <td class="payment-context-cell">' + helpers.escapeHtml(supplierContext.settlementDisplay || "-") + "</td>",
          '  <td class="numeric-cell">' + helpers.escapeHtml(String(supplierContext.invoiceCount || 0)) + "</td>",
          '  <td class="numeric-cell">' + helpers.escapeHtml(helpers.formatCurrency(allocatedAmount)) + "</td>",
          '  <td><select class="payment-account-select" data-payment-account-supplier="' + helpers.escapeHtml(supplierContext.id || "") + '"' +
            (state.paymentCreation.isBusy || !supplierContext.id ? " disabled" : "") + ">" + selectOptions.join("") + "</select></td>",
          "</tr>"
        ].join("");
      }).join("") : '<tr><td colspan="7" class="table-empty">No supplier context available for this payment.</td></tr>';
      elements.invoicePaymentSupplierAccountsTableWrap.hidden = !context;
      elements.invoicePaymentSupplierAccountsList.innerHTML = supplierAccountRows;

      elements.invoicePaymentAllocationsList.innerHTML = context ? context.invoices.map(function (invoice) {
        var allocatedValue = form.allocations && form.allocations[invoice.id] !== undefined
          ? roundCurrency(form.allocations[invoice.id])
          : roundCurrency(invoice.pendingAmount);

        return [
          "<tr>",
          '  <td class="payment-context-cell"><strong>' + helpers.escapeHtml(invoice.number) + "</strong></td>",
          "  <td>" + helpers.escapeHtml(invoice.supplierName || "-") + "</td>",
          "  <td>" + helpers.escapeHtml(invoice.bookingName || "-") + "</td>",
          "  <td>" + helpers.escapeHtml(invoice.mfsp || "-") + "</td>",
          "  <td>" + helpers.escapeHtml(invoice.settlementName || "-") + "</td>",
          "  <td>" + helpers.escapeHtml(helpers.formatDate(invoice.date)) + "</td>",
          '  <td class="numeric-cell">' + helpers.escapeHtml(helpers.formatCurrency(invoice.pendingAmount)) + "</td>",
          '  <td class="numeric-cell"><input type="number" min="0" step="0.01" data-payment-allocation="' + helpers.escapeHtml(invoice.id) + '" value="' + helpers.escapeHtml(String(allocatedValue)) + '"></td>',
          "</tr>"
        ].join("");
      }).join("") : "";

      elements.invoicePaymentName.disabled = state.paymentCreation.isBusy;
      elements.invoicePaymentDate.disabled = state.paymentCreation.isBusy;
      elements.invoicePaymentAccount.disabled = state.paymentCreation.isBusy || !context || !headerPaymentAccounts.length;
      elements.invoicePaymentAccountToggle.disabled = state.paymentCreation.isBusy || !context || !headerPaymentAccounts.length;
      elements.invoicePaymentClose.disabled = state.paymentCreation.isBusy;
      elements.invoicePaymentCancel.disabled = state.paymentCreation.isBusy;
      elements.invoicePaymentSubmit.disabled = state.paymentCreation.isBusy || !context;
      elements.invoicePaymentSubmit.textContent = state.paymentCreation.isBusy
        ? (context && context.hasMixedInvoiceTypes ? "Creating payment and refund..." : (context && context.movementType === PAYMENT_MOVEMENT_TYPES.supplierRefund ? "Creating refund..." : "Creating payment..."))
        : (context && context.hasMixedInvoiceTypes ? "Create payment and refund" : (context && context.movementType === PAYMENT_MOVEMENT_TYPES.supplierRefund ? "Create refund" : "Create payment"));

      Array.prototype.forEach.call(
        elements.invoicePaymentAllocationsList.querySelectorAll("input[data-payment-allocation]"),
        function (input) {
          input.disabled = state.paymentCreation.isBusy;
        }
      );
    }

    function closeCreatePaymentPanel() {
      state.paymentCreation.isOpen = false;
      state.paymentCreation.isBusy = false;
      resetInvoicePaymentForm();
      renderer.showError("");
      renderAll();
    }

    async function openCreatePaymentPanel() {
      var invoicesView = buildInvoicesView();
      var selectedInvoices = invoicesView.selectedFilteredRecords;
      var paymentContext;

      renderer.showError("");
      paymentContext = buildInvoicePaymentContext(selectedInvoices);

      if (paymentContext.error) {
        renderer.showError(paymentContext.error);
        return;
      }

      state.paymentCreation.isOpen = true;
      state.paymentCreation.isBusy = true;
      renderAll();
      renderer.showNotice("Preparing supplier payment form...", {
        isLoading: true
      });

      try {
        await ensurePaymentAccountsLoaded();
        state.paymentCreation.context = paymentContext.context;
        state.paymentCreation.form = buildDefaultInvoicePaymentForm(paymentContext.context);
        state.paymentCreation.isBusy = false;
        renderAll();

        if (elements.invoicePaymentPanel && typeof elements.invoicePaymentPanel.scrollIntoView === "function") {
          elements.invoicePaymentPanel.scrollIntoView({
            behavior: "smooth",
            block: "start"
          });
        }
      } catch (error) {
        debugError("openCreatePaymentPanel failed", error);
        state.paymentCreation.isBusy = false;
        renderer.showError(error.message || "Could not prepare the supplier payment form.");
        renderAll();
      } finally {
        renderer.showNotice("");
      }
    }

    function onInvoicePaymentAllocationChange(event) {
      var target = event.target;
      var invoiceId;
      var parsedValue;

      if (!target || !target.getAttribute) {
        return;
      }

      invoiceId = target.getAttribute("data-payment-allocation");

      if (!invoiceId) {
        return;
      }

      parsedValue = roundCurrency(Number(target.value));
      state.paymentCreation.form.allocations[invoiceId] = Number.isFinite(parsedValue) && parsedValue >= 0 ? parsedValue : 0;
      renderInvoicePaymentPanel();
    }

    function onInvoicePaymentSupplierAccountChange(event) {
      var target = event.target;
      var supplierId;

      if (!target || !target.getAttribute) {
        return;
      }

      supplierId = target.getAttribute("data-payment-account-supplier");

      if (!supplierId) {
        return;
      }

      state.paymentCreation.form.paymentAccountsBySupplier[supplierId] = target.value || "";
      renderInvoicePaymentPanel();
    }

    function validateInvoicePaymentSubmission() {
      var context = state.paymentCreation.context;
      var allocations = {};
      var paymentAccountsBySupplier = {};
      var headerPaymentAccountId = String(state.paymentCreation.form.headerPaymentAccountId || "").trim();
      var allowedHeaderPaymentAccountIds = getAvailableHeaderPaymentAccounts().map(function (account) {
        return String(account && account.id || "");
      });
      var totalAmount = 0;
      var currentSelectionIds = buildInvoicesView().selectedFilteredRecords.map(function (invoice) {
        return String(invoice.id);
      }).sort();
      var contextIds = (context && context.invoices ? context.invoices : []).map(function (invoice) {
        return String(invoice.id);
      }).sort();

      if (!context || !context.invoices.length) {
        return {
          error: "There is no supplier payment context to submit."
        };
      }

      if (currentSelectionIds.join("|") !== contextIds.join("|")) {
        return {
          error: "The selected invoices changed while the payment form was open. Close it and open it again from the current selection."
        };
      }

      if (!String(state.paymentCreation.form.paymentDate || "").trim()) {
        return {
          error: "Enter a payment date before creating the payment."
        };
      }

      if (!headerPaymentAccountId) {
        return {
          error: "Select a payment account before creating the payment."
        };
      }

      if (allowedHeaderPaymentAccountIds.indexOf(headerPaymentAccountId) === -1) {
        return {
          error: "The selected payment account is no longer available. Choose another Own payment account."
        };
      }

      context.invoices.forEach(function (invoice) {
        var rawValue = state.paymentCreation.form.allocations[invoice.id];
        var allocatedValue = roundCurrency(Number(rawValue));

        if (!Number.isFinite(allocatedValue) || allocatedValue < 0) {
          allocations.__error = "Allocated amounts must be valid positive numbers or zero.";
          return;
        }

        if (allocatedValue > roundCurrency(invoice.pendingAmount)) {
          allocations.__error = "Allocated amount for " + invoice.number + " cannot be greater than its pending amount.";
          return;
        }

        allocations[invoice.id] = allocatedValue;
        totalAmount += allocatedValue;
      });

      totalAmount = roundCurrency(totalAmount);

      if (allocations.__error) {
        return {
          error: allocations.__error
        };
      }

      if (totalAmount <= 0) {
        return {
          error: "Allocate more than EUR 0.00 before creating the payment."
        };
      }

      var netAmount = getInvoicePaymentNetAmount(context, allocations);

      if (netAmount === 0) {
        return {
          error: "The selected invoices net to EUR 0.00. Record this as a settlement without a bank payment."
        };
      }

      (context.suppliers || []).forEach(function (supplierContext) {
        var selectedAccountId;
        var allowedAccountIds;
        var fallbackAccountId;

        if (!supplierContext.id) {
          return;
        }

        selectedAccountId = String(
          state.paymentCreation.form.paymentAccountsBySupplier &&
          state.paymentCreation.form.paymentAccountsBySupplier[supplierContext.id] !== undefined
            ? state.paymentCreation.form.paymentAccountsBySupplier[supplierContext.id]
            : ""
        );
        allowedAccountIds = getAllowedPaymentAccountsForSupplier(supplierContext.id).map(function (account) {
          return String(account.id || "");
        });

        if (selectedAccountId && allowedAccountIds.indexOf(selectedAccountId) === -1) {
          fallbackAccountId = String(getPreferredPaymentAccountIdForSupplier(supplierContext.id) || "");

          if (fallbackAccountId && allowedAccountIds.indexOf(fallbackAccountId) !== -1) {
            selectedAccountId = fallbackAccountId;
            state.paymentCreation.form.paymentAccountsBySupplier[supplierContext.id] = fallbackAccountId;
          } else {
            paymentAccountsBySupplier.__error = "Selected payment account for " + supplierContext.name + " is no longer available.";
            return;
          }
        }

        paymentAccountsBySupplier[supplierContext.id] = selectedAccountId;
      });

      if (paymentAccountsBySupplier.__error) {
        return {
          error: paymentAccountsBySupplier.__error
        };
      }

      return {
        allocations: allocations,
        headerPaymentAccountId: headerPaymentAccountId,
        totalAmount: totalAmount,
        netAmount: netAmount,
        movementType: netAmount < 0 ? PAYMENT_MOVEMENT_TYPES.supplierRefund : PAYMENT_MOVEMENT_TYPES.outbound,
        paymentAccountsBySupplier: paymentAccountsBySupplier
      };
    }

    async function ensureSupplierPaymentAccountForPayment(supplierId) {
      var accountingResponse;
      var accountingOutput;
      var accountingFallback;
      var accountingAccountId = "";
      var paymentResponse;
      var paymentOutput;
      var paymentFallback;
      var paymentAccountId = "";

      if (!supplierId) {
        return "";
      }

      accountingResponse = await crm.executeFunction(ENSURE_SUPPLIER_ACCOUNTING_ACCOUNT_FUNCTION, {
        supplierId: supplierId
      });
      accountingOutput = getFunctionOutputObject(accountingResponse) || {};
      accountingFallback = getFunctionResponseResult(accountingResponse);

      if (accountingOutput.error) {
        throw new Error(accountingOutput.message || accountingFallback.message || "Supplier accounting account could not be prepared.");
      }

      accountingAccountId = String(accountingOutput.accounting_account_id || "").trim();

      paymentResponse = await crm.executeFunction(ENSURE_SUPPLIER_PAYMENT_ACCOUNT_FUNCTION, {
        supplierId: supplierId,
        accountingAccountId: accountingAccountId
      });
      paymentOutput = getFunctionOutputObject(paymentResponse) || {};
      paymentFallback = getFunctionResponseResult(paymentResponse);

      if (paymentOutput.error) {
        throw new Error(paymentOutput.message || paymentFallback.message || "Supplier payment account could not be prepared.");
      }

      paymentAccountId = String(paymentOutput.payment_account_id || "").trim();

      if (paymentAccountId) {
        try {
          await ensureSupplierDefaultPaymentAccountAssigned(supplierId, paymentAccountId);
        } catch (defaultPaymentAccountError) {
          debugError("ensureSupplierDefaultPaymentAccountAssigned failed", defaultPaymentAccountError, {
            supplierId: supplierId,
            paymentAccountId: paymentAccountId
          });
        }
      }

      return paymentAccountId;
    }

    async function resolvePaymentAccountsForPaymentCreate(context, paymentAccountsBySupplier, allocations) {
      var resolved = Object.assign({}, paymentAccountsBySupplier || {});
      var hasChanges = false;
      var activeSupplierIds = {};
      var index;
      var supplierContext;
      var supplierId;
      var selectedAccountId;
      var defaultAccountId;
      var ensuredAccountId;

      (context && context.invoices ? context.invoices : []).forEach(function (invoice) {
        var invoiceId = String(invoice && invoice.id || "").trim();
        var allocatedAmount = roundCurrency(Number(allocations && allocations[invoiceId]));
        var activeSupplierId = String(invoice && invoice.supplierId || "").trim();

        if (!invoiceId || !activeSupplierId || !Number.isFinite(allocatedAmount) || allocatedAmount <= 0) {
          return;
        }

        activeSupplierIds[activeSupplierId] = true;
      });

      for (index = 0; index < (context && context.suppliers ? context.suppliers.length : 0); index += 1) {
        supplierContext = context.suppliers[index];
        supplierId = String(supplierContext && supplierContext.id || "").trim();

        if (!supplierId || !activeSupplierIds[supplierId]) {
          continue;
        }

        selectedAccountId = String(resolved[supplierId] || "").trim();

        if (selectedAccountId) {
          continue;
        }

        defaultAccountId = String(getPreferredPaymentAccountIdForSupplier(supplierId) || "").trim();

        if (defaultAccountId) {
          resolved[supplierId] = defaultAccountId;
          hasChanges = true;
          continue;
        }

        ensuredAccountId = await ensureSupplierPaymentAccountForPayment(supplierId);

        if (ensuredAccountId) {
          resolved[supplierId] = ensuredAccountId;
          hasChanges = true;
        }
      }

      return {
        paymentAccountsBySupplier: resolved,
        hasChanges: hasChanges
      };
    }

    function buildSupplierPaymentCreateEntries(context, allocations, paymentAccountsBySupplier) {
      var invoicesById = {};
      var entries = [];
      var supplierIds = [];
      var supplierNames = [];
      var bookingIds = [];
      var bookingNames = [];
      var settlementIds = [];
      var settlementNames = [];

      state.records.invoices.forEach(function (invoice) {
        if (invoice && invoice.id) {
          invoicesById[String(invoice.id)] = invoice;
        }
      });

      (context && context.invoices ? context.invoices : []).forEach(function (invoiceSummary) {
        var invoiceId = String(invoiceSummary && invoiceSummary.id || "").trim();
        var allocatedAmount = roundCurrency(Number(allocations && allocations[invoiceId]));
        var invoiceRecord;
        var supplierId;
        var supplierName;
        var bookingId;
        var bookingName;
        var settlementId;
        var settlementName;
        var paymentAccountId;

        if (!invoiceId || !Number.isFinite(allocatedAmount) || allocatedAmount <= 0) {
          return;
        }

        invoiceRecord = invoicesById[invoiceId];

        if (!invoiceRecord) {
          throw new Error("Invoice " + invoiceId + " is no longer available in the current session. Refresh and try again.");
        }

        supplierId = getInvoiceSupplierId(invoiceRecord);
        supplierName = getSupplierNameFromInvoice(invoiceRecord);
        bookingId = getBookingIdFromInvoice(invoiceRecord);
        bookingName = getBookingNameFromInvoice(invoiceRecord);
        settlementId = getInvoiceSettlementId(invoiceRecord);
        settlementName = getInvoiceSettlementName(invoiceRecord);
        paymentAccountId = supplierId ? String(paymentAccountsBySupplier && paymentAccountsBySupplier[supplierId] || "").trim() : "";

        entries.push({
          invoiceId: invoiceId,
          invoiceNumber: helpers.getInvoiceDisplayNumber(invoiceRecord, FIELD_CANDIDATES),
          invoiceRecord: invoiceRecord,
          allocatedAmount: allocatedAmount,
          supplierId: supplierId,
          supplierName: supplierName,
          bookingId: bookingId,
          bookingName: bookingName,
          settlementId: settlementId,
          settlementName: settlementName,
          ezusReference: String(invoiceRecord.Ezus_Supplier_Reference || "").trim(),
          mfsp: getMfspFromInvoice(invoiceRecord) || "",
          invoiceDate: invoiceRecord.Invoice_Date || "",
          invoiceStatus: invoiceRecord.Status || "",
          isCreditNote: isCreditNoteInvoice(invoiceRecord),
          paymentAccountId: paymentAccountId
        });

        if (supplierId) {
          supplierIds.push(supplierId);
        }
        if (supplierName) {
          supplierNames.push(supplierName);
        }
        if (bookingId) {
          bookingIds.push(bookingId);
        }
        if (bookingName) {
          bookingNames.push(bookingName);
        }
        if (settlementId) {
          settlementIds.push(settlementId);
        }
        if (settlementName) {
          settlementNames.push(settlementName);
        }
      });

      supplierIds = helpers.uniqueNonEmpty(supplierIds);
      supplierNames = helpers.sortStrings(helpers.uniqueNonEmpty(supplierNames));
      bookingIds = helpers.uniqueNonEmpty(bookingIds);
      bookingNames = helpers.sortStrings(helpers.uniqueNonEmpty(bookingNames));
      settlementIds = helpers.uniqueNonEmpty(settlementIds);
      settlementNames = helpers.sortStrings(helpers.uniqueNonEmpty(settlementNames));

      return {
        entries: entries,
        supplierIds: supplierIds,
        supplierNames: supplierNames,
        bookingIds: bookingIds,
        bookingNames: bookingNames,
        settlementIds: settlementIds,
        settlementNames: settlementNames,
        contextMode: (
          supplierNames.length <= 1 &&
          bookingNames.length <= 1 &&
          settlementNames.length <= 1
        ) ? "Single" : "Mixed",
        contextSummary: buildPaymentContextSummaryText({
          supplierNames: supplierNames,
          bookingNames: bookingNames,
          settlementNames: settlementNames
        })
      };
    }

    function buildSupplierPaymentPayload(paymentData, createEntriesResult) {
      var payload = {
        Name: paymentData.Name,
        Payment_Amount: roundCurrency(paymentData.Payment_Amount),
        Payment_Date: paymentData.Payment_Date,
        Status: paymentData.Status,
        Accounting_Status: paymentData.Accounting_Status,
        Context_Mode: createEntriesResult.contextMode,
        Supplier_Count: createEntriesResult.supplierIds.length,
        Booking_Count: createEntriesResult.bookingIds.length,
        Settlement_Count: createEntriesResult.settlementIds.length,
        Allocation_Count: createEntriesResult.entries.length,
        Context_Summary: createEntriesResult.contextSummary
      };

      if (paymentData.Movement_Type) {
        payload.Movement_Type = paymentData.Movement_Type;
      }

      if (paymentData.Payment_Account) {
        payload.Payment_Account = {
          id: paymentData.Payment_Account
        };
      }

      return payload;
    }

    function buildSupplierPaymentAllocationPayload(paymentId, paymentReference, paymentData, entry) {
      var payload = {
        Name: paymentReference + " - " + entry.invoiceNumber,
        Supplier_Payment: { id: paymentId },
        Supplier_Invoice: { id: entry.invoiceId },
        Allocated_Amount: entry.allocatedAmount,
        Allocation_Date: paymentData.Payment_Date,
        Payment_Date: paymentData.Payment_Date,
        Payment_Status: paymentData.Status,
        Payment_Accounting_Status: paymentData.Accounting_Status
      };

      payload.Movement_Type = entry.isCreditNote ? PAYMENT_MOVEMENT_TYPES.supplierRefund : PAYMENT_MOVEMENT_TYPES.outbound;

      if (entry.supplierId) {
        payload.Supplier = { id: entry.supplierId };
      }
      if (entry.supplierName) {
        payload.Supplier_Name = entry.supplierName;
      }
      if (entry.bookingId) {
        payload.Booking = { id: entry.bookingId };
      }
      if (entry.settlementId) {
        payload.Supplier_Settlement = { id: entry.settlementId };
      }
      if (entry.ezusReference) {
        payload.Ezus_Supplier_Reference = entry.ezusReference;
      }
      if (entry.mfsp) {
        payload.MFSP_Reference = entry.mfsp;
      }
      if (entry.invoiceDate) {
        payload.Invoice_Date = entry.invoiceDate;
      }
      if (entry.invoiceStatus) {
        payload.Invoice_Status = entry.invoiceStatus;
      }
      if (entry.paymentAccountId) {
        payload.Payment_Account = { id: entry.paymentAccountId };
      }

      return payload;
    }

    async function updateInvoiceAfterAllocation(entry) {
      var invoice = entry.invoiceRecord;
      var currentPaid = roundCurrency(getInvoicePaidAmount(invoice));
      var nextPaid = roundCurrency(currentPaid + entry.allocatedAmount);
      var totalPayable = roundCurrency(helpers.getInvoiceTotalAmount(invoice, FIELD_CANDIDATES));
      var payload = {
        Amount_Paid: nextPaid
      };

      if (totalPayable > 0 && nextPaid >= totalPayable) {
        payload.Status = "Paid";
      } else if (nextPaid > 0) {
        payload.Status = "Partially Paid";
      }

      assertCrmMutationSucceeded(
        await crm.updateRecord(MODULES.invoices, entry.invoiceId, payload),
        "Zoho CRM did not confirm the invoice update after payment allocation."
      );
    }

    async function createSupplierPaymentAllocations(paymentId, paymentData, createEntriesResult) {
      var allocationIds = [];
      var successfulEntries = [];
      var errors = [];
      var index;
      var entry;
      var response;
      var created;

      for (index = 0; index < createEntriesResult.entries.length; index += 1) {
        entry = createEntriesResult.entries[index];

        try {
          response = await crm.insertRecord(
            MODULES.payAllocations,
            buildSupplierPaymentAllocationPayload(paymentId, paymentData.Name, paymentData, entry)
          );
          created = assertCrmMutationSucceeded(response, "Zoho CRM did not confirm one payment allocation.");

          if (created.details && created.details.id) {
            allocationIds.push(created.details.id);
          }

          await updateInvoiceAfterAllocation(entry);
          successfulEntries.push(entry);
        } catch (error) {
          errors.push(entry.invoiceNumber + ": " + (error.message || "Unknown allocation error"));
        }
      }

      return {
        allocationIds: allocationIds,
        successfulEntries: successfulEntries,
        errors: errors
      };
    }

    async function refreshInvoicesAndPaymentsAfterSupplierPayment() {
      var shouldReloadInvoicesView = state.currentTab === "invoices" && state.views.invoices.hasLoaded;
      var shouldReloadPaymentsView = state.currentTab === "payments" && state.views.payments.hasLoaded;

      state.dashboard.loaded = false;
      state.dashboard.pendingInvoices = [];
      state.dashboard.pendingSettlements = [];
      state.loaded.settlements = false;
      state.loaded.invoices = false;
      state.loaded.payments = false;
      state.loaded.payAllocations = false;
      state.views.invoices.hasMore = false;
      state.views.payments.hasMore = false;
      state.views.invoices.hasLoaded = false;
      state.views.payments.hasLoaded = false;
      state.records.settlements = [];
      state.records.invoices = [];
      state.records.payments = [];
      state.records.payAllocations = [];
      resetPaymentRelationshipIndexes();

      await ensurePayAllocationsLoaded();

      if (shouldReloadInvoicesView) {
        await refreshInvoicesTabData({
          loadedFlag: true
        });
      }

      if (shouldReloadPaymentsView) {
        await refreshPaymentsTabData({
          loadedFlag: true
        });
      }

      if (state.supplierId) {
        state.supplierInvoices = await loadInvoicesForSupplier(state.supplierId);
        state.supplierPayments = await loadPaymentsForSupplier(state.supplierId);
      }
    }

    async function onCreateSupplierPaymentSubmit(event) {
      var validation;
      var context = state.paymentCreation.context;
      var paymentData = {};
      var response;
      var selectedDetailId = state.views.invoices.selectedDetailId;
      var created = false;
      var paymentRecord;
      var paymentId = "";
      var settlementUpdateMessage = "";
      var accountingSyncMessage = "";
      var resolvedPaymentAccountsResult;
      var createEntriesResult;
      var allocationResult;
      var allocationWarning = "";
      var paymentAccountsRefreshNeeded = false;
      var invoiceAccountingSyncResult = null;
      var invoiceAccountingSyncMessage = "";

      event.preventDefault();
      renderer.showError("");

      validation = validateInvoicePaymentSubmission();

      if (validation.error) {
        renderer.showError(validation.error);
        return;
      }

      paymentData.Name = (state.paymentCreation.form.name || "").trim();
      paymentData.Payment_Date = state.paymentCreation.form.paymentDate;
      paymentData.Payment_Account = validation.headerPaymentAccountId;
      paymentData.Payment_Amount = Math.abs(validation.netAmount);
      paymentData.Movement_Type = validation.movementType;
      paymentData.Status = state.paymentCreation.form.status || "Paid";
      paymentData.Accounting_Status = state.paymentCreation.form.accountingStatus || "Pending";
      paymentData.allocations = validation.allocations;

      if (!paymentData.Name) {
        paymentData.Name = buildDefaultPaymentReference(paymentData.Payment_Date);
      }

      state.paymentCreation.isBusy = true;
      renderAll();
      renderer.showNotice(
        context && context.hasMixedInvoiceTypes
          ? "Creating net supplier settlement..."
          : paymentData.Movement_Type === PAYMENT_MOVEMENT_TYPES.supplierRefund
          ? "Creating supplier refund..."
          : "Creating supplier payment...",
        {
          isLoading: true
        }
      );

      try {
        resolvedPaymentAccountsResult = await resolvePaymentAccountsForPaymentCreate(context, validation.paymentAccountsBySupplier, validation.allocations);
        paymentData.Payment_Accounts_By_Supplier = resolvedPaymentAccountsResult.paymentAccountsBySupplier;
        paymentAccountsRefreshNeeded = resolvedPaymentAccountsResult.hasChanges;
        createEntriesResult = buildSupplierPaymentCreateEntries(context, validation.allocations, paymentData.Payment_Accounts_By_Supplier);

        if (!createEntriesResult.entries.length) {
          throw new Error("No positive invoice allocations were found to create the payment.");
        }

        response = await crm.insertRecord(MODULES.payments, buildSupplierPaymentPayload(paymentData, createEntriesResult));
        paymentRecord = assertCrmMutationSucceeded(response, "Zoho CRM did not confirm the supplier payment creation.");
        paymentId = paymentRecord.details && paymentRecord.details.id ? String(paymentRecord.details.id) : "";

        if (!paymentId) {
          throw new Error("Zoho CRM did not return the created payment ID.");
        }

        allocationResult = await createSupplierPaymentAllocations(paymentId, paymentData, createEntriesResult);

        if (!allocationResult.successfulEntries.length) {
          try {
            await crm.deleteRecord(MODULES.payments, paymentId);
          } catch (paymentDeleteError) {
            debugError("rollback payment delete failed", paymentDeleteError, { paymentId: paymentId });
          }
          throw new Error("The payment was not kept because none of its allocations could be created. " + allocationResult.errors.join(" "));
        }

        if (allocationResult.successfulEntries.length !== createEntriesResult.entries.length) {
          var successfulNetAmount = roundCurrency(allocationResult.successfulEntries.reduce(function (sum, entry) {
            return sum + (entry.isCreditNote ? -entry.allocatedAmount : entry.allocatedAmount);
          }, 0));
          paymentData.Payment_Amount = Math.abs(successfulNetAmount);
          paymentData.Movement_Type = successfulNetAmount < 0 ? PAYMENT_MOVEMENT_TYPES.supplierRefund : PAYMENT_MOVEMENT_TYPES.outbound;
          assertCrmMutationSucceeded(
            await crm.updateRecord(MODULES.payments, paymentId, buildSupplierPaymentPayload(paymentData, buildSupplierPaymentCreateEntries(
              { invoices: allocationResult.successfulEntries.map(function (entry) { return { id: entry.invoiceId }; }) },
              allocationResult.successfulEntries.reduce(function (map, entry) { map[entry.invoiceId] = entry.allocatedAmount; return map; }, {}),
              paymentData.Payment_Accounts_By_Supplier
            ))),
            "Zoho CRM did not confirm the supplier payment update after partial allocation creation."
          );
          allocationWarning = " Some allocations could not be created: " + allocationResult.errors.join(" ");
        }

        context.invoices.forEach(function (invoice) {
          delete state.invoiceAllocationsByInvoiceId[invoice.id];
        });

        state.views.invoices.selectedIds = {};
        closeCreatePaymentPanel();
        await refreshInvoicesAndPaymentsAfterSupplierPayment();
        if (paymentAccountsRefreshNeeded) {
          state.loaded.paymentAccounts = false;
          state.records.paymentAccounts = [];
          await ensurePaymentAccountsLoaded();
        }
        state.views.payments.selectedId = paymentId;
        invalidateInvoiceCreateSettlementCache();

        try {
          await recalculateSettlementTotalsForSettlementIds(getUniqueSettlementIdsFromInvoices(context.invoices));
        } catch (settlementUpdateError) {
          debugError("recalculate settlement totals after payment create failed", settlementUpdateError, {
            paymentId: paymentId,
            settlementIds: getUniqueSettlementIdsFromInvoices(context.invoices)
          });
          settlementUpdateMessage = " The related settlement totals could not be updated automatically.";
        }

        if (!allocationWarning) {
          try {
            invoiceAccountingSyncResult = await syncAccountingEntriesForInvoices(
              allocationResult.successfulEntries.map(function (entry) {
                return entry.invoiceId;
              }),
              {
                continueOnError: true
              }
            );

            if (invoiceAccountingSyncResult.failures.length) {
              invoiceAccountingSyncMessage = " Some invoice accounting entries could not be synced automatically. Use Sync entry manually on those invoices.";
            } else if (invoiceAccountingSyncResult.syncedInvoiceIds.length) {
              invoiceAccountingSyncMessage = " Invoice accounting entries synced automatically.";
            }
          } catch (invoiceAccountingSyncError) {
            debugError("auto sync invoice accounting after payment create failed", invoiceAccountingSyncError, {
              paymentId: paymentId,
              invoiceIds: allocationResult.successfulEntries.map(function (entry) {
                return entry.invoiceId;
              })
            });
            invoiceAccountingSyncMessage = " Invoice accounting entries could not be synced automatically. Use Sync entry manually on the invoices.";
          }

          try {
            await syncAccountingEntryForPayment(paymentId, {
              silent: true,
              skipRender: true
            });
            accountingSyncMessage = " Accounting entry synced automatically.";
          } catch (accountingSyncError) {
            debugError("auto sync accounting after payment create failed", accountingSyncError, {
              paymentId: paymentId
            });
            accountingSyncMessage = " Accounting entry could not be synced automatically. Use Sync entry manually.";
          }
        } else {
          invoiceAccountingSyncMessage = " Invoice accounting entries were not auto-synced because some allocations need review. Use Sync entry manually on the invoices.";
          accountingSyncMessage = " Accounting entry was not auto-synced because some allocations need review. Use Sync entry manually.";
        }

        renderAll();

        if (selectedDetailId) {
          await ensureInvoiceAllocationsLoaded(selectedDetailId, true);
        }

        created = true;
        renderer.showNotice(
          (context && context.hasMixedInvoiceTypes
            ? "Net supplier settlement created successfully."
            : paymentData.Movement_Type === PAYMENT_MOVEMENT_TYPES.supplierRefund
              ? "Supplier refund created successfully."
              : "Supplier payment created successfully.") + settlementUpdateMessage + invoiceAccountingSyncMessage + accountingSyncMessage + allocationWarning,
          {
            tone: allocationWarning ||
              settlementUpdateMessage ||
              (invoiceAccountingSyncMessage && invoiceAccountingSyncMessage.indexOf("could not") !== -1) ||
              (invoiceAccountingSyncMessage && invoiceAccountingSyncMessage.indexOf("were not") !== -1) ||
              (accountingSyncMessage && accountingSyncMessage.indexOf("could not") !== -1)
              ? "neutral"
              : "success"
          }
        );
      } catch (error) {
        debugError("onCreateSupplierPaymentSubmit failed", error);
        state.paymentCreation.isBusy = false;
        renderer.showNotice("");
        renderer.showError(
          error.message || (
            paymentData.Movement_Type === PAYMENT_MOVEMENT_TYPES.supplierRefund
              ? "Could not create the supplier refund."
              : "Could not create the supplier payment."
          )
        );
        renderAll();
      } finally {
        if (!created && state.paymentCreation.isBusy) {
          renderer.showNotice("");
        }
      }
    }

    return {
      resetInvoicePaymentForm: resetInvoicePaymentForm,
      renderInvoicePaymentPanel: renderInvoicePaymentPanel,
      closeCreatePaymentPanel: closeCreatePaymentPanel,
      openCreatePaymentPanel: openCreatePaymentPanel,
      onInvoicePaymentAllocationChange: onInvoicePaymentAllocationChange,
      onInvoicePaymentSupplierAccountChange: onInvoicePaymentSupplierAccountChange,
      onInvoicePaymentHeaderAccountFocus: onInvoicePaymentHeaderAccountFocus,
      onInvoicePaymentHeaderAccountInput: onInvoicePaymentHeaderAccountInput,
      onInvoicePaymentHeaderAccountKeydown: onInvoicePaymentHeaderAccountKeydown,
      onInvoicePaymentHeaderAccountBlur: onInvoicePaymentHeaderAccountBlur,
      onInvoicePaymentHeaderAccountToggleClick: onInvoicePaymentHeaderAccountToggleClick,
      onInvoicePaymentHeaderAccountDropdownPointerDown: onInvoicePaymentHeaderAccountDropdownPointerDown,
      onInvoicePaymentHeaderAccountDropdownClick: onInvoicePaymentHeaderAccountDropdownClick,
      onCreateSupplierPaymentSubmit: onCreateSupplierPaymentSubmit,
      refreshInvoicesAndPaymentsAfterSupplierPayment: refreshInvoicesAndPaymentsAfterSupplierPayment
    };
  };
}(window));
